// -------------------------------------------------------------
// Component : Remove Area Uniform Loads
// Author    : Generated by ChatGPT
// Target    : Rhino 7/8 + Grasshopper, .NET Framework 4.8 (x64)
// Depends   : Grasshopper, ETABSv1 (COM)  [Embed Interop Types = False]
// Panel     : "MGT" / "3.0 Area Object Modelling"
// -------------------------------------------------------------
// Inputs (ordered):
//   0) run         (bool, item)    Rising-edge trigger.
//   1) sapModel    (ETABSv1.cSapModel, item)  ETABS model from Attach component.
//   2) areaNames   (string, list)  Area object names to process. Blank/dup ignored (case-insensitive).
//   3) loadPatterns(string, list)  OPTIONAL filters. Empty ⇒ remove all uniform loads on each area.
//
// Outputs:
//   0) messages    (string, list)  Summary + diagnostics.
//
// Behavior Notes:
//   • Queries existing uniform loads via AreaObj.GetLoadUniform (per object).
//   • When loadPatterns is empty/omitted, all uniform load assignments are removed.
//   • When loadPatterns are provided, only matching load pattern assignments are removed (case-insensitive).
//   • Loads are removed per unique (pattern, direction) combination.
//   • Attempts to unlock the model before editing. Areas not found are reported.
//   • When run is false or not toggled, the component replays the last output messages.
// -------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Drawing;
using ETABSv1;
using Grasshopper.Kernel;
using static MGT.ComponentShared;

namespace MGT
{
    public class GhcRemoveLoadUniformOnAreas : GH_Component
    {
        private bool _lastRun;
        private readonly List<string> _lastMessages = new List<string> { "No previous run. Toggle 'run' to remove loads." };

        public GhcRemoveLoadUniformOnAreas()
          : base(
                "Remove Area Uniform Loads",
                "RemoveAreaUDL",
                "Remove uniform load assignments from ETABS area objects (per object mode).",
                "MGT",
                "3.0 Area Object Modelling")
        {
        }

        public override Guid ComponentGuid => new Guid("3b2b3f1a-2dc0-4c34-94d4-3fd101f729af");

        protected override Bitmap Icon => null;

        protected override void RegisterInputParams(GH_InputParamManager p)
        {
            p.AddBooleanParameter("run", "run", "Rising-edge trigger; executes when this turns True.", GH_ParamAccess.item, false);
            p.AddGenericParameter("sapModel", "sapModel", "ETABS cSapModel from the Attach component.", GH_ParamAccess.item);
            int areaIndex = p.AddTextParameter(
                "areaNames",
                "areaNames",
                "Area object names to process. Blank entries are ignored. Duplicate names are removed (case-insensitive).",
                GH_ParamAccess.list);
            p[areaIndex].Optional = true;

            int patternIndex = p.AddTextParameter(
                "loadPatterns",
                "loadPatterns",
                "Optional load pattern filters. Leave empty to remove all uniform loads from the areas.",
                GH_ParamAccess.list);
            p[patternIndex].Optional = true;
        }

        protected override void RegisterOutputParams(GH_OutputParamManager p)
        {
            p.AddTextParameter("messages", "messages", "Summary and diagnostic messages.", GH_ParamAccess.list);
        }

        protected override void SolveInstance(IGH_DataAccess da)
        {
            bool run = false;
            cSapModel sapModel = null;
            List<string> areaNames = new List<string>();
            List<string> loadPatterns = new List<string>();

            da.GetData(0, ref run);
            da.GetData(1, ref sapModel);
            da.GetDataList(2, areaNames);
            da.GetDataList(3, loadPatterns);

            bool rising = !_lastRun && run;
            if (!rising)
            {
                da.SetDataList(0, _lastMessages);
                _lastRun = run;
                return;
            }

            List<string> messages = new List<string>();

            try
            {
                if (sapModel == null)
                {
                    throw new InvalidOperationException("sapModel is null. Wire it from the Attach component.");
                }

                List<string> cleanedAreas = NormalizeDistinct(areaNames);
                if (cleanedAreas.Count == 0)
                {
                    messages.Add("No valid area names provided.");
                    PushOutputs(da, messages, run);
                    return;
                }

                List<string> cleanedPatterns = NormalizeDistinct(loadPatterns);
                HashSet<string> patternSet = null;
                if (cleanedPatterns.Count > 0)
                {
                    patternSet = new HashSet<string>(cleanedPatterns, StringComparer.OrdinalIgnoreCase);
                }

                EnsureModelUnlocked(sapModel);
                HashSet<string> existingNames = TryGetExistingAreaNames(sapModel);

                int areasMissing = 0;
                int queryFailures = 0;
                int targetedLoads = 0;
                int removedLoads = 0;
                int failedRemovals = 0;
                HashSet<string> areasModified = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                List<string> missingNames = new List<string>();
                List<string> queryFailedNames = new List<string>();
                List<string> failedAssignments = new List<string>();

                foreach (string rawName in cleanedAreas)
                {
                    if (string.IsNullOrWhiteSpace(rawName))
                    {
                        continue;
                    }

                    string areaName = rawName.Trim();
                    if (areaName.Length == 0)
                    {
                        continue;
                    }

                    if (existingNames != null && !existingNames.Contains(areaName))
                    {
                        areasMissing++;
                        missingNames.Add(areaName);
                        continue;
                    }

                    var loadResult = CollectUniformLoads(sapModel, areaName);
                    if (!loadResult.success)
                    {
                        queryFailures++;
                        queryFailedNames.Add(areaName);
                        continue;
                    }

                    if (loadResult.entries.Count == 0)
                    {
                        continue;
                    }

                    HashSet<string> processedPatterns = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                    foreach (UniformLoadEntry entry in loadResult.entries)
                    {
                        string entryPattern = entry.LoadPattern ?? string.Empty;
                        bool matches = patternSet == null || patternSet.Contains(entryPattern);
                        if (!matches)
                        {
                            continue;
                        }

                        string normalizedPattern = entryPattern ?? string.Empty;
                        if (!processedPatterns.Add(normalizedPattern))
                        {
                            continue;
                        }

                        targetedLoads++;

                        if (TryDeleteLoad(sapModel, areaName, normalizedPattern))
                        {
                            removedLoads++;
                            areasModified.Add(areaName);
                        }
                        else
                        {
                            failedRemovals++;
                            failedAssignments.Add($"{areaName}:{normalizedPattern}");
                        }
                    }
                }

                if (removedLoads > 0)
                {
                    messages.Add($"Removed {Plural(removedLoads, "uniform load assignment")} from {Plural(areasModified.Count, "area")}.");
                }
                else if (targetedLoads > 0)
                {
                    messages.Add($"Attempted to remove {Plural(targetedLoads, "uniform load assignment")}, but none succeeded.");
                }
                else
                {
                    if (patternSet == null)
                    {
                        messages.Add("No uniform loads found on the specified areas.");
                    }
                    else
                    {
                        string summary = FormatLoadPatternSummary(cleanedPatterns);
                        messages.Add($"No uniform loads matched {summary} on the specified areas.");
                    }
                }

                if (failedRemovals > 0)
                {
                    messages.Add("Failed removals (area:pattern): " + string.Join(", ", failedAssignments));
                }

                if (areasMissing > 0)
                {
                    messages.Add("Missing areas: " + string.Join(", ", missingNames));
                }

                if (queryFailures > 0)
                {
                    messages.Add("Load query failed for areas: " + string.Join(", ", queryFailedNames));
                }

                try
                {
                    if (removedLoads > 0)
                    {
                        sapModel.View.RefreshView(0, false);
                    }
                }
                catch
                {
                    // ignored
                }
            }
            catch (Exception ex)
            {
                messages.Add("Error: " + ex.Message);
            }

            PushOutputs(da, messages, run);
        }

        private void PushOutputs(IGH_DataAccess da, List<string> messages, bool currentRunState)
        {
            da.SetDataList(0, messages);

            _lastMessages.Clear();
            _lastMessages.AddRange(messages);
            _lastRun = currentRunState;
        }

        private static (bool success, List<UniformLoadEntry> entries) CollectUniformLoads(cSapModel model, string areaName)
        {
            List<UniformLoadEntry> entries = new List<UniformLoadEntry>();
            if (model == null || string.IsNullOrWhiteSpace(areaName))
            {
                return (false, entries);
            }

            try
            {
                int count = 0;
                string[] names = null;
                string[] loadPatterns = null;
                string[] coordinateSystems = null;
                int[] directions = null;
                double[] values = null;

                int ret = model.AreaObj.GetLoadUniform(
                    areaName,
                    ref count,
                    ref names,
                    ref loadPatterns,
                    ref coordinateSystems,
                    ref directions,
                    ref values,
                    eItemType.Objects);

                if (ret != 0)
                {
                    return (false, entries);
                }

                if (count <= 0 || loadPatterns == null)
                {
                    return (true, entries);
                }

                for (int i = 0; i < count; i++)
                {
                    string pattern = SafeArrayValue(loadPatterns, i);
                    if (!string.IsNullOrWhiteSpace(pattern))
                    {
                        pattern = pattern.Trim();
                    }

                    UniformLoadEntry entry = new UniformLoadEntry
                    {
                        AreaName = areaName,
                        LoadPattern = pattern,
                        CoordinateSystem = SafeArrayValue(coordinateSystems, i),
                        Value = SafeArrayValue(values, i)
                    };

                    entries.Add(entry);
                }

                return (true, entries);
            }
            catch
            {
                return (false, entries);
            }
        }

        private static bool TryDeleteLoad(cSapModel model, string areaName, string loadPattern)
        {
            if (model == null)
            {
                return false;
            }

            try
            {
                int ret = model.AreaObj.DeleteLoadUniform(
                    areaName ?? string.Empty,
                    loadPattern ?? string.Empty,
                    eItemType.Objects);

                return ret == 0;
            }
            catch
            {
                return false;
            }
        }

        private static string FormatLoadPatternSummary(IReadOnlyList<string> filters)
        {
            if (filters == null || filters.Count == 0)
            {
                return string.Empty;
            }

            if (filters.Count == 1)
            {
                return $"load pattern \"{filters[0]}\"";
            }

            return $"load patterns ({string.Join(", ", filters)})";
        }

        private static string SafeArrayValue(string[] source, int index)
        {
            if (source == null || index < 0 || index >= source.Length)
            {
                return string.Empty;
            }

            return source[index] ?? string.Empty;
        }

        private static double SafeArrayValue(double[] source, int index)
        {
            if (source == null || index < 0 || index >= source.Length)
            {
                return 0.0;
            }

            double value = source[index];
            if (double.IsNaN(value) || double.IsInfinity(value))
            {
                return 0.0;
            }

            return value;
        }

        private static HashSet<string> TryGetExistingAreaNames(cSapModel model)
        {
            if (model == null)
            {
                return null;
            }

            try
            {
                int count = 0;
                string[] names = null;
                int ret = model.AreaObj.GetNameList(ref count, ref names);
                if (ret != 0)
                {
                    return null;
                }

                HashSet<string> result = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                if (names == null)
                {
                    return result;
                }

                for (int i = 0; i < names.Length; i++)
                {
                    string nm = names[i];
                    if (!string.IsNullOrWhiteSpace(nm))
                    {
                        result.Add(nm.Trim());
                    }
                }

                return result;
            }
            catch
            {
                return null;
            }
        }

        private class UniformLoadEntry
        {
            public string AreaName { get; set; }
            public string LoadPattern { get; set; }
            public string CoordinateSystem { get; set; }
            public double Value { get; set; }
        }
    }
}
